vich_uploader:
    db_driver: orm

    mappings:
        performance:
            uri_prefix: '%app.path.note_documents%'
            upload_destination: '%kernel.project_dir%/public%app.path.note_documents%'
